
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.navi.backend.parser_lexer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREEN = 22;
  public static final int TIMES = 15;
  public static final int SQUARE = 10;
  public static final int PLUS = 13;
  public static final int RPAREN = 18;
  public static final int DIGIT = 29;
  public static final int CURVE = 8;
  public static final int BLACK = 25;
  public static final int DIVISION = 16;
  public static final int PINK = 26;
  public static final int CIRCLE = 9;
  public static final int ANIMAR = 4;
  public static final int BLUE = 19;
  public static final int OBJETO = 5;
  public static final int LPAREN = 17;
  public static final int ID = 28;
  public static final int RED = 20;
  public static final int GRAFICAR = 3;
  public static final int COMMA = 2;
  public static final int POLYGON = 12;
  public static final int SKY = 23;
  public static final int EOF = 0;
  public static final int CYAN = 24;
  public static final int RECTANGLE = 11;
  public static final int MINUS = 14;
  public static final int error = 1;
  public static final int YELLOW = 21;
  public static final int LINE = 7;
  public static final int ANTERIOR = 6;
  public static final int PURPLE = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMMA",
  "GRAFICAR",
  "ANIMAR",
  "OBJETO",
  "ANTERIOR",
  "LINE",
  "CURVE",
  "CIRCLE",
  "SQUARE",
  "RECTANGLE",
  "POLYGON",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVISION",
  "LPAREN",
  "RPAREN",
  "BLUE",
  "RED",
  "YELLOW",
  "GREEN",
  "SKY",
  "CYAN",
  "BLACK",
  "PINK",
  "PURPLE",
  "ID",
  "DIGIT"
  };
}

